CREATE TABLE bot_settings (
    id BIGINT PRIMARY KEY,
    token VARCHAR(255),
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO bot_settings (id, token, enabled)
VALUES (1, NULL, FALSE)
ON DUPLICATE KEY UPDATE id = id;

CREATE TABLE bot_logs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    level VARCHAR(32) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
